### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by AxForest** [Gurkengewuerz/nodebb-plugin-teamspeak-verify#2]
How to config the plugin? 
cant find any menu. 
Please share these information.

**Comment by Gurkengewuerz** [comment]
Hey @AxForest this plugin wasn't updated since two years this was due to no interest in the nodebb development.
But thanks to @Zerefdev who forked this plugin and fixed the compatibility i merged his changes to the master and published version *1.1.0* at npm which should be now available at the plugin search in nodebb!

The plugin was tested under nodebb v1.12.x and worked fine for me!
You can find the configuration under Plugins > Teamspeak
